//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagimovApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int IdClient { get; set; }
        public string LastNameClient { get; set; }
        public string FirstNameClient { get; set; }
        public string MiddleNameClient { get; set; }
        public string NumberPhoneClient { get; set; }
        public int IdTypeChat { get; set; }
    
        public virtual TypeClient TypeClient { get; set; }
    }
}
