//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagimovApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsAndMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailsAndMaterial()
        {
            this.ProductAndDetails = new HashSet<ProductAndDetails>();
        }
    
        public int IdDetailsAndMaterial { get; set; }
        public int IdRawMaterial { get; set; }
        public int IdDetail { get; set; }
    
        public virtual Details Details { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAndDetails> ProductAndDetails { get; set; }
    }
}
