//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagimovApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAndDetails
    {
        public int IdProductAndDetails { get; set; }
        public int IdProduct { get; set; }
        public int IdDetailsAndRawMaterial { get; set; }
    
        public virtual DetailsAndMaterial DetailsAndMaterial { get; set; }
        public virtual Product Product { get; set; }
    }
}
