//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagimovApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductAndDetails = new HashSet<ProductAndDetails>();
        }
    
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public string IssueNumberProduct { get; set; }
        public decimal CostProduct { get; set; }
        public System.DateTime GuaranteeProduct { get; set; }
        public int QualityProduct { get; set; }
        public int IdWorkshop { get; set; }
    
        public virtual Workshop Workshop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAndDetails> ProductAndDetails { get; set; }
    }
}
