//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagimovApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyMaterial
    {
        public int IdSupply { get; set; }
        public int IdRawMaterial { get; set; }
        public int IdProvider { get; set; }
        public string CountSupply { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
    }
}
