//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagimovApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.ScheduleOfFilms = new HashSet<ScheduleOfFilms>();
        }
    
        public int IdTicket { get; set; }
        public int IdFilm { get; set; }
        public System.DateTime StartingDate { get; set; }
        public int IdHall { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime SellingDate { get; set; }
        public int RowNumber { get; set; }
        public int PlaceNumber { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Halls Halls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleOfFilms> ScheduleOfFilms { get; set; }
    }
}
