//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RagimovApp.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerInfo
    {
        public int IdInfoAbout { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int IdAdressOfLiving { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public string Education { get; set; }
        public string WorkExpirience { get; set; }
        public int IdCinema { get; set; }
        public int IdUser { get; set; }
        public byte[] WorkerPhoto { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual User User { get; set; }
        public virtual WorkerAdress WorkerAdress { get; set; }
    }
}
